mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote_http, name='vote'),
]

mysite/polls/models.py
import datetime
#from polls.APIdolarOficial import claseDolar
#from polls.APIdolarOficial import apiFer
from secrets import choice
from time import time
from xmlrpc.client import boolean
from django.db import models
from django.utils import timezone
from django.contrib import admin

from polls.tucson import apiFer

# Create your models here.
class Question (models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('dia publicado')
    #valor_dolar_oficial = claseDolar().oficial()
    #valor_dolar_blue = claseDolar().blue()
    #apiFer()
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='publicado recientemente?'
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now




class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    #valor_dolar_oficial_choice = claseDolar().oficial()
    #valor_dolar_blue_choice = claseDolar().blue()
    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from logging import exception
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.shortcuts import get_object_or_404,render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from setuptools import Command


from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]



class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

class Resultado:
    @classmethod
    def exitoso(cls):
        return cls()

    def __init__(self):
        self._errores = []

    def agregar_error(self, mensaje_de_error):
        self._errores.append(mensaje_de_error)

    def es_exitoso(self):
        return not self.hay_errores()

    def errores(self):
        return self._errores

    def hay_errores(self):
        return len(self._errores) > 0

def obtener_model_a_partir_de_id(resultado, id, model_class):
    try:
        model = model_class.objects.get(pk=id)
    except Exception:
        resultado.agregar_error(f"Tu {model_class} id es invalido")
    return model

def obtener_choice_correspondiente_a_question(resultado, question, choice_id):
    try:
        selected_choice = question.choice_set.get(pk=choice_id)
    except Exception:
        resultado.agregar_error("tu choice no corresponde a la question")
    return selected_choice

def vote_http(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        choice_id = request.POST['choice']
        agregar_un_voto(question_id, choice_id)
    except(KeyError, Choice.DoesNotExist):
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "No seleccionaste una choice",
            })
    else:
        #selected_choice.votes += 1
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

def agregar_un_voto(question_id, choice_id):
    resultado = Resultado()
    # entre estos comentarios no deberia ser parte de vote porque vote es la accion directamente
    question = obtener_model_a_partir_de_id(resultado, question_id, Question)
    choice = obtener_model_a_partir_de_id(resultado, choice_id, Choice)
    if resultado.hay_errores():
        return resultado()
    # a partir de aca abajo es la accion de votar posta
    try:
        selected_choice = obtener_choice_correspondiente_a_question(resultado, question, choice_id)
        selected_choice.votes += 1
        selected_choice.save()
    except Exception:
        resultado.agregar_error("hubo un error al votar")
    return resultado

    
def vote_http_new(request, question_id):
    choice_id = request.POST['choice']
    resultado = agregar_un_voto(question_id, choice_id)
    return calcular_respuesta_http(request, resultado, question_id)

def vote_http_new_v2(request, question_id):
    choice_id = request.POST['choice']
    command = AgregarUnVoto(question_id, choice_id)
    resultado = command.execute()
    return calcular_respuesta_http(request, resultado, question_id)

class AgregarUnVoto():
    def __init__(self, question_id, choice_id):
        self._question_id = question_id
        self._choice_id = choice_id

    def execute(self):
        resultado = Resultado()
        # entre estos comentarios no deberia ser parte de vote porque vote es la accion directamente
        question = obtener_model_a_partir_de_id(resultado, self._question_id, Question)
        choice = obtener_model_a_partir_de_id(resultado, self._choice_id, Choice)
        if resultado.hay_errores():
            return resultado()
        # a partir de aca abajo es la accion de votar posta
        try:
            selected_choice = obtener_choice_correspondiente_a_question(resultado, question, self._choice_id)
            selected_choice.votes += 1
            selected_choice.save()
        except Exception:
            resultado.agregar_error("hubo un error al votar")
        return resultado


def calcular_respuesta_http(request, resultado, question_id):
    if resultado.es_exitoso():
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))
    string_errores = errores_concatenados(resultado)
    return render(request, 'polls/detail.html',{
        'question': question_id,
        'error_message': string_errores,
    })

def errores_concatenados(resultado):
    texto_con_errores = ""
    for error in resultado.errores():
        texto_con_errores = texto_con_errores + " | " + error
    return texto_con_errores

mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{question.question_text}} DOLAR HOY: {{question.valor_dolar_oficial}} - {{ question.valor_dolar_blue }}</h1></legend>
        {% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }} DOLAR: {{ choice.valor_dolar_oficial_choice }} - {{ choice.valor_dolar_blue_choice }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
    {% load static %}

    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }} | DOLAR OFICIAL HOY --->>{{ question.valor_dolar_oficial }} | DOLAR BLUE HOY--->>{{ question.valor_dolar_blue }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} voto{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
    
    <a href="{% url 'polls:detail' question.id %}">Votar otra vez?</a>
</form>
</body>
</html>